### ISSUE TITLE
numpy.distutils.fcompiler.CompilerNotFound

### ISSUE THREAD

**Issue by jycr753** [Homebrew/homebrew-python#184] opened 2014-12-15 10:40 UTC
I don't quiet understand this error since according to this [issue](https://github.com/Homebrew/homebrew-python/issues/133) in homewbrew it can be fixed by installing gcc , but I do have this installed correctly with version gcc-4.9.2.

The full error looks like this.

```
==> python setup.py build --fcompiler=gnu95 install --prefix=/usr/local/Cellar/n
  File "/private/tmp/numpy-PAz3bw/numpy-1.9.1/numpy/distutils/fcompiler/gnu.py", line 197, in get_flags_opt
    v = self.get_version()
  File "/private/tmp/numpy-PAz3bw/numpy-1.9.1/numpy/distutils/fcompiler/__init__.py", line 434, in get_version
    raise CompilerNotFound()
numpy.distutils.fcompiler.CompilerNotFound
```
But I dont quiet understand the error... any ideas?
thanks

**Comment by shpedoikal** [comment] 2015-01-07 22:51
Same issue here although none of the above fixes it.  My brew gist-logs numpy is here: https://gist.github.com/0be5665315f755e7e761

```
[key@kyoder-macbook:~]$ which gfortran
/usr/local/bin/gfortran
[key@kyoder-macbook:~]$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/4.9.1/libexec/gcc/x86_64-apple-darwin13.2.0/4.9.1/lto-wrapper
Target: x86_64-apple-darwin13.2.0
Configured with: ../configure --build=x86_64-apple-darwin13.2.0 --prefix=/usr/local/Cellar/gcc/4.9.1 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-cloog=/usr/local/opt/cloog --with-isl=/usr/local/opt/isl --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc 4.9.1' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.1 (Homebrew gcc 4.9.1)
```

**Comment by shpedoikal** [comment] 2015-01-07 23:01
...aaand updating gcc has fixed the issue for me. :-)

**Comment by tdsmith** [comment] 2015-03-20 16:21
Duplicate of #170.

**Closed by tdsmith** 2015-03-20 16:21 UTC
