### ISSUE TITLE
numpy: CompilerNotFound

### ISSUE THREAD

**Issue by fabiencastan** [Homebrew/homebrew-python#176] opened 2014-11-10 22:29 UTC
Hi,
```brew install numpy``` fails. I use it on travis osx.

```
==> python setup.py install --prefix=/usr/local/Cellar/numpy/1.9.0 --single-vers
==> python setup.py build --fcompiler=gnu95 install --prefix=/usr/local/Cellar/n
  File "/private/tmp/numpy-05GBiS/numpy-1.9.0/numpy/distutils/fcompiler/gnu.py", line 197, in get_flags_opt
    v = self.get_version()
  File "/private/tmp/numpy-05GBiS/numpy-1.9.0/numpy/distutils/fcompiler/__init__.py", line 434, in get_version
    raise CompilerNotFound()
numpy.distutils.fcompiler.CompilerNotFound
```

The only solution is to install it using ```pip install numpy```...
But I want people to be able to install my project (which use numpy) with a simple brew install.

Regards,
Fabien

**Comment by tdsmith** [comment] 2015-03-20 16:20
Duplicate of #170.

**Closed by tdsmith** 2015-03-20 16:20 UTC
